chore: setup gitignore
woowacourse-teams/2021-gpu-is-mine pull request #14
Opened 2021-07-05 10:03 UTC by knae11

Closes #13 

hello World 띄웠는데 확인 요청드립니다 :)

2021-07-05 10:43 UTC, sjpark-dev commented
PR 돌려봤는데 잘 돌아가네요 :)

다만, 몇가지 확인 부탁드립니다.

1. spring boot 2.4.5가 아닌 2.4.3으로 설정하셨는데 의도하신 것인지 궁금하네요.
2. 커밋 메세지는 한글로 작성!

2021-07-05 14:59 UTC, bigsaigon333 commented
추가로 PR은 fork한 개인 레포지토리에서 upstream으로 쏘면 좋을거 같아요~!

(현재 upstream/back-end -> upstream/main 으로 보여서 첨언했어요)

2021-07-05 15:06 UTC, bigsaigon333 requested changes
1.  예전에 POSIX에서 line을 개행문자로 끝이 나는 시퀀스로 정의하였기 때문에 이런 정의에 따르면 파일의 마지막에 newline이 없으면 마지막 줄은 POSIX에서 정의한 line의 정의에 맞지 않게 됩니다.
따라서 line by line 으로 텍스트를 읽는 프로그램의 경우, 마지막 줄을 line으로 보지 않아 처리하지 않을 수 있다고 합니다~~ 참고용으로 코멘트 달아보았어요 

https://velog.io/@bigsaigon333/Level1-javascript-racingcar#1-%EC%99%9C-%ED%8C%8C%EC%9D%BC%EC%9D%98-%EB%A7%88%EC%A7%80%EB%A7%89%EC%9D%80-newline%EC%9C%BC%EB%A1%9C-%EB%81%9D%EB%82%98%EC%95%BC-%ED%95%A0%EA%B9%8C

2. JS 프로젝트에서는 prettier와 같은 도구를 사용해서 자동으로 코드 포맷팅을 하는게 일반적인데

java에도 유사한 게 있으면 적용해보면 좋을거 같아요! 

https://www.jetbrains.com/help/idea/prettier.html#prettier_before_you_start

https://github.com/jhipster/prettier-java

2021-07-05 15:06 UTC, bigsaigon333 commented on .gitignore
> +.idea
마지막 행에 개행문자를 넣어서 `No newline at end of file`을 없애주세요!

https://minz.dev/19

2021-07-05 15:06 UTC, bigsaigon333 commented on back-end/.gitignore
> +
마지막 행에는 개행문자 하나만 넣어주세요! :+1:

2021-07-05 15:06 UTC, bigsaigon333 commented on back-end/build.gradle
> +}
newline at EOF!

2021-07-06 00:04 UTC, knae11 commented
> 추가로 PR은 fork한 개인 레포지토리에서 upstream으로 쏘면 좋을거 같아요~!
> 
> (현재 upstream/back-end -> upstream/main 으로 보여서 첨언했어요)

@bigsaigon333   현재 저장소에서 브랜치파서 PR 날리고 해당 브랜치는 삭제되면 좋을 것 같다고 생각했어요. 개인으로 fork 해야할까 생각이 드는데 어떻게 생각하는지 의견 모아보면 좋을 것 같아용~ㅎㅎ

2021-07-06 00:05 UTC, knae11 commented
@sjpark-dev 스프링부터 버전 반영하였습니다!

2021-07-06 00:43 UTC, knae11 commented
@bigsaigon333 개행자료 감사합니다~~ :) 반영하였어요! 

백엔드 분들 https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95
해당링크 참고하면 모든 파일에 개행 넣을 수 있어여~~
컨밴션 논의합시다!

2021-07-06 01:10 UTC, merged