feat: worker 기능 구현
woowacourse-teams/2021-gpu-is-mine pull request #152
Opened 2021-07-23 07:35 UTC by knae11

resolve #138 

# 변경사항
- 기존 GpuServer에서 찾기 내용이 liveServer 만 가져오게 되어있어서 메소드명 수정
- 구현하다보니 url 변경의 필요성이 느껴저 일부 변형하고 해당내용 [api 정리 엑셀](https://docs.google.com/spreadsheets/d/12JlH36Oltc_EOo3woEob-Pz6llY2SkQ9vsrL1TsdMPg/edit?usp=sharing)에 반영 

# 구현사항
- Job의 상태 변경
- 해당 서버의 가장 먼저 들어온 WAITING Job 가져오는 기능
- GpuServer의 상태변경

# 테스트
- JobRepository 쿼리 메소드 테스트
- WorkerServiceTest
- WorkerAcceptanceTest

2021-07-23 14:51 UTC, wannte requested changes
개인적으로 생각했을 때, 가장 난이도가 높은 부분이라고 생각합니다.

그럼에도 잘 구현해 주셨네요!

본문에도 남겼다 싶이 배럴, 코기 팀이 생각하는 Api 흐름도를 명시해주면 더 좋을 것 같아요!

2021-07-23 14:51 UTC, wannte commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +    public GpuServerResponses findAllLiveServer(Long labId) {
findAll->findAllLIveServer 로 변경해주셨군요! deleted 여부를 메소드 명으로 확인할 수 있겠네요!

한 가지, 제가 처음 LiveServer 라는 명명을 봤을 때, 살아있는 서버, isOn = True, 즉 켜져 있는 서버만을 쿼리해온다라고 착각했습니다.
deleted 와 isOn 비슷해보이는 두 개의 값이 모두 존재해서 발생하는 문제라 생각하는데요,

findAllUndeletedServer 의 사용은 어떨까요?

2021-07-23 14:51 UTC, wannte commented on back-end/src/test/java/admin/worker/ui/WorkerAcceptanceTest.java
> +    }
요 부분도 코기랑 말을 많이 했던 부분인데, 내부의 의존적인 코드가 의미하는 바를 이제야 파악했네요!

제가 생각하는 방식으로 일부를 수정해보면 다음과 같습니다

```java
    @Override
    @BeforeEach
    public void setUp() {
        super.setUp();
        labRequest = new LabRequest("lab1");
        Long labId = LAB_생성_요청_후_생성_ID_리턴(labRequest);
        
        gpuBoardRequest = new GpuBoardRequest("NVIDIA42", 600L);

        serverRequest = new GpuServerRequest("server1",  1024L, 1024L, gpuBoardRequest);
        Long serverId = GPU_SERVER_생성_요청_후_생성_ID_리턴(serverRequest);
        
        memberRequest = new MemberRequest("email@email.com", "password", "name1", "MANAGER", labId);
        Long memberId = MEMBER_생성_요청_후_생성_ID_리턴(memberRequest);
...
```

각각의 *_생성_요청_후_생성_ID_리턴 의 경우 다른 Acceptance에서 이미 구현된 부분들을 활용하면 쉽게 만들 수 있지 않을까 생각합니다.

제가 생각하는 인수 테스트는 
request 요청 -> 서버를 통해 -> response 응답
이 정보들의 조합으로만 이루어진 테스트입니다. 서버는 Black Box로 그 내부가 어떤 구성으로 이루어진지는 배재하고 진행하는 테스트를 의도했습니다!

이건 제가 생각하는 부분이니 굳이 반영하지 않아도 좋습니다. 지금의 테스트만으로도 충분히 기능하고 있다 생각합니다.MemberAcceptance를 확인하시면 제가 생각하는 방식을 알 수 있을 것 같아요!

코기와의 대화에서 서로 다른 곳을 바라보고 이야기를 했다라는 생각이 드네요!

2021-07-23 16:08 UTC, sjpark-dev reviewed
안녕하세요 배럴 😊
작성하신 코드 잘 봤습니다. 👍
어려운 부분 잘 구현하셨네요.

제가 드리고 싶은 피드백 대부분이 완태랑 겹쳐서 코멘트는 별도로 남기지 않겠습니다.

2021-07-23 16:52 UTC, ecsimsw commented on back-end/src/main/java/admin/worker/application/WorkerService.java
> +        }
어... @완태 이 부분은 저도 불명확하네요.
이게 WorkerException이 좋을까요? 서버에 대기 중인 잡이 없는데 WorkerException이 좋을지..

제안을 드리는 방식으로 리뷰를 작성하려고 다짐했는데 정말 모르겠네요. 이 부분은.
그래도 있는 코드 안에서 찾는다면 저라면 ServerException이나 배럴의 코드처럼 JobException을 줄 것 같아요.

2021-07-23 16:54 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +    public GpuServerResponses findAllLiveServer(Long labId) {
와우... 이거 정말 어렵고 저도 바꾸고 싶었는데 배럴이 용기내주었네요.

수정 의견 제시가 아니라, 응원 댓글입니다.
진짜 헷갈렸는데 다른 사람의 코드라 용기를 못 냈었거든요.

2021-07-23 17:12 UTC, ecsimsw commented on back-end/src/test/java/admin/worker/ui/WorkerAcceptanceTest.java
> +    }
음 저도 그럼 요기서 제 생각 정리를... 

저도 완태의 한 사이클 전체를 확인할 수 있는 테스트가 필요하다는데 동의합니다!!
정말 꼭 필요한 부분이라고 생각합니다. 
다만 저는 아직 내부 비즈니스 로직이 구현이 덜 된 상태에서 인수 테스트를 반드시 작성하는 것이 옳은가 에 대한 생각이 큽니다..

저는 우선은 빠르게 기능 구현에 집중하되, 비즈니스 로직이 많이 바뀔 것이라고 생각했습니다. 제 UI 테스트는 프론트엔드와의 규약이 맞는지 확인 정도였지, QueueService가 있는지, JobService가 잘 작동하는지는 테스트 관심 포인트에 없었거든요.

프론트엔드와의 규약이라면 딱 API 명세 확인 정도일 것 같습니다. 프론트 팀과 협의했던 어떤 기능을 수행에서 어떤 Path에, 어떤 요청 쿼리와 body를 주고, 어떤 헤더로 오면 -> 우리는 프론트 팀과 협의했던대로 어떤 꼴의 응답을 줄거야~ 
딱 문서화 정도로 말이지요.

다시 한번 말씀드리지만, 그렇다고 요청 한 싸이클에서 애플리케이션 정상 동작 전체를 확인하는 테스트 코드는 필요없다! 가 아니었습니다.
다만, 저는 아직 비즈니스 로직이 확립이 안되었고 변동 사항이 어마무시할 것 같다고 생각했는데, 지금 전체 서비스를 확인하는 섬세한 테스트 코드가 필요할까였었습니다.

이전에 회원 정보, 잡 큐에 대한 개념이 전무했던 상황에서 @에드와 JobAcceptance 테스트를 짰던 경험이 생각나네요. 지금 회원 인증 하나가 포함된 상황에서 해당 인수 테스트 중 살아남을 테스트 코드가 있을까요? 어느 정도 구조를 잡고 운영을 위한 시나리오 테스트를 하는 것이 좋지 않을까요?

정답은 없다고 생각하고 있습니다.

2021-07-23 17:31 UTC, ecsimsw commented on back-end/src/main/java/admin/worker/ui/WorkerController.java
> +}
맞습니다. 필요하다고 생각합니다!!

2021-07-24 07:40 UTC, sjpark-dev commented on back-end/src/main/java/admin/worker/application/WorkerService.java
> +    public JobResponse popJobByServerId(Long serverId) {
배럴~

지금은 worker가 job을 pop하고 해당 job의 status를 Running으로 바꾸기 위해서 다시 요청을 해야하는데요
Worker가 job을 팝해가면 해당 job의 상태를 자동으로 Running으로 만들어 줄 수 있을 것 같은데
어떻게 생각하시나요?

GM서버를 구현하는 입장에서 요청을 두번하는게 좋을지 한번의 요청으로 처리하면 좋을지 모르겠어서 의견을 물어봅니다. 😊

2021-07-24 10:39 UTC, ecsimsw commented on back-end/src/main/java/admin/worker/application/WorkerService.java
> +    public JobResponse popJobByServerId(Long serverId) {
오옷 좋은 피드백에 칭찬 답글 남깁니다.

이 부분 배럴이 고민하고 신경 쓴 부분인데 잘 찾으셨군요!!

2021-07-25 06:06 UTC, wannte commented on back-end/src/main/java/admin/worker/application/WorkerService.java
> +        }
나도 이거 보고 "아차" 했습니다.

단순히 도메인의 구분에 따라 구분을 했었던 것 같아요!

저도 지금 와서 의문이 드는 지점이 사용자가 누구냐의 따라 도메인이 구분 된다?라는 부분이에요! (두 가지 종류의 client를 다뤄본 적이 없기 때문에 이 부분은 모호하네요, 지금처럼 worker로 구분하는것이 좋은지, 아니면 JobService에서 모든 경우를 다 처리해주는 것이 좋을지!

JobException에서 NO_WAITING_JOB 에러의 분리는 필요해보이네요!

2021-07-25 06:29 UTC, wannte commented on back-end/src/test/java/admin/worker/ui/WorkerAcceptanceTest.java
> +    }
좋은 의견 감사합니다!

아직 명확하게 정의되지 않은 도메인에 대해서 그 인수 테스트를 짜는 것 자체가 불가능할 수도 있겠네요,
(제가 구현한 부분은 반면에, 가장 기초적인 부분이라 다른 구현에 의존적이지 않아 그런 부분에서는 편했고요)

개인적인 생각으로는 이런 경우라면 Acceptance 테스트를 제외하고 테스트를 작성해도 충분할 것 같네요!
이후에 구조가 어느 정도 명확해 지면 그 때 구현을 이어가도 될 것 같습니다.

많은 변화가 발생하지도 않을 것 같고요!

2021-07-25 08:26 UTC, knae11 commented on back-end/src/main/java/admin/worker/application/WorkerService.java
> +
야호~

2021-07-25 08:32 UTC, knae11 commented on back-end/src/main/java/admin/job/domain/repository/JobRepository.java
> +    List<Job> findAllByBoardIdAndStatusByOrderById(Long boardId, JobStatus status);
메소드명으로는 참고하지 않는 듯 합니다 :)  혹시 제안하는 메소드명이 있을까요?ㅎㅎㅎ 제시해주면 반영해볼게요~ㅎㅎㅎ

2021-07-25 08:36 UTC, knae11 commented on back-end/src/main/java/admin/worker/application/WorkerService.java
> +    public JobResponse popJobByServerId(Long serverId) {
제가 이부분에서 고민해서 2번의 요청으로 처리했던 이유는 다음과 같아요.

http 통신이기 때문에 보내준다고 과연 `RUNNING` 상태가 될까 의문이 들었습니다. 유실가능성이 있기 때문에, 서버입장에서는 클라이언트가 받았는지 여부를 알수가 없다고 판단했어요. Worker가 받지 못해서 job 요청을 여러번 할 수도 있다고 생각해요. 이럴 때, RUNNING 상태로 바꾸고, 다음 요청을 한다면 계속 다음 job이 나갈 것 같았어요.(실제로는 이전 job이 실행되지 않았을 수도 있는데 말이죠)

제가 2번의 요청으로 처리한 이유인데, 혹시 다른 의견 있다면 제시해주세요~ :-D

2021-07-25 08:41 UTC, knae11 commented on back-end/src/test/java/admin/worker/ui/WorkerAcceptanceTest.java
> +    }
두분의 의견 감사해요! 👍 

제 생각에는 DB에 값을 넣어주고 원하는 인수테스트만 작성하는게 좋다고 생각했어요!  우리가 WorkerAcceptanceTest 에서 확인하고 싶은 것은 Worker와 관련된 API에서 잘 동작하는가? 라고 생각했기 때문이에요.

그래서 DB에 직접 값들을 넣어주고 Worker 와 관련된 API만 확인해주었어요 :) 

저는 한 사이클을 도는 AcceptanceTest는 필요하다고 생각하지만 테스트를 위해 필요한 다른 도메인의 값 셋팅조차 API로 해야할까에는 의문입니다! :)

2021-07-25 09:30 UTC, sjpark-dev commented on back-end/src/main/java/admin/job/domain/repository/JobRepository.java
> +    List<Job> findAllByBoardIdAndStatusByOrderById(Long boardId, JobStatus status);
참고를 안한다면 첫번째 `By`를 뺀
`findAllByBoardIdAndStatusOrderById`를 추천하겠습니다!

2021-07-25 09:32 UTC, sjpark-dev commented on back-end/src/main/java/admin/worker/application/WorkerService.java
> +    public JobResponse popJobByServerId(Long serverId) {
이유가 납듯이 되네요 👍

2021-07-25 11:13 UTC, knae11 commented on back-end/src/main/java/admin/job/domain/repository/JobRepository.java
> +    List<Job> findAllByBoardIdAndStatusByOrderById(Long boardId, JobStatus status);
반영했어요~ :)

2021-07-25 11:15 UTC, knae11 commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +    public GpuServerResponses findAllLiveServer(Long labId) {
좋습니다~ 피드백 내용 반영했어요!

2021-07-25 11:19 UTC, knae11 commented on back-end/src/main/java/admin/worker/application/WorkerService.java
> +        }
해당 내용 반영하였습니다! :) 추가했어요

2021-07-25 11:27 UTC, knae11 commented
# Worker에서 API사용 예상 시나리오

## 서버 상태  
- Worker는 n 분마다 자신이 살아있음을 알린다.(PUT `/api/workers/gpus/{serverId}/status`)
- 자신의 살아있는 지 여부를 엔티티에서 수정하고, lastResponse 를 갱신하여 업데이트 한다.
- 만약 Client 가 서버를 조회했을 때, lastResponse로 부터 n 분이상 지나면 서버는 죽었다고 판단한다.
- 위와 같이 하는 이유는 서버가 죽으면 자신이 죽었다고 알리지 못하기 때문이다.

## 예약 job 가져가기
- 해당 서버에 예약되어 있는 job중 가장 최신 것을 가져온다.
- 실행하고 있던 job이 종료되면 (GET `/api/workers/gpus/{serverId}/job`) 를 호출하여 다음 job을 가져간다.
- 만약, 예약되어 있는 Job이 없다고 한다면 n분마다 GET 요청을 해야한다.

## 예약을 가져갔음을 알림
- GET 요청으로 예약되어 있는 job을 가져갔다면, 실행하고 있음을 알린다.
- PUT `/api/workers/jobs/{jobId}/status` 를 보내 자신이 job을 실행하고 있음을 알리고, 해당 job을 RUNNING 상태로 변경한다.
>제가 이부분에서 고민해서 2번의 요청으로 처리했던 이유는 다음과 같아요.

>http 통신이기 때문에 보내준다고 과연 RUNNING 상태가 될까 의문이 들었습니다. 유실가능성이 있기 때문에, 서버입장에서는 클라이언트가 받았는지 여부를 알수가 없다고 판단했어요. Worker가 받지 못해서 job 요청을 여러번 할 수도 있다고 생각해요. 이럴 때, RUNNING 상태로 바꾸고, 다음 요청을 한다면 계속 다음 job이 나갈 것 같았어요.(실제로는 이전 job이 실행되지 않았을 수도 있는데 말이죠)

2021-07-25 11:28 UTC, knae11 commented on back-end/src/main/java/admin/worker/ui/WorkerController.java
> +}
아래 커멘트로 정리했어요 :)  [여기](https://github.com/woowacourse-teams/2021-gpu-is-mine/pull/152#issuecomment-886187552)

2021-07-25 11:37 UTC, sjpark-dev approved these changes

2021-07-26 02:42 UTC, wannte commented on back-end/src/test/java/admin/worker/ui/WorkerAcceptanceTest.java
> +    }
@knae11 요런 의도를 가지고 있었군요!
그런 목적이라면 지금의 구현으로도 충분하겠네요! :+1:

2021-07-26 02:53 UTC, wannte approved these changes
수정 확인했어요! 수고많았습니다!

2021-07-26 04:41 UTC, merged