chore: back-end github action filter 추가
woowacourse-teams/2021-gpu-is-mine pull request #160
Opened 2021-07-24 12:39 UTC by wannte

동동꺼 배꼈어요 리뷰해줘요 ㅋ.ㅋ

하나의 github action으로 front/back end를 진행하도록 만들어 볼 수도 있겠네요.(사실 이 방법이 Computing 자원을 효율적으로 사용하는 action이라 생각되네요)

filter에 따라서 각각의 pipeline이 진행되도록!

시각적으로 front/back 을 구분하여 보여주는 측면에서는 지금의 방식이 더 좋을 거 같다 라는 생각도 들고요!

이 방법을 jenkins에도 존재할 것 같아서 알아보면 좋을듯!

2021-07-24 12:40 UTC, ecsimsw commented
이게 어떤 겁니까?

2021-07-24 12:45 UTC, wannte commented
@ecsimsw 동동이 github action pipeline을 도입해주었어요!

front-end 파일 밑 또는 back-end 파일 밑에 변경이 감지되었을 때만 각각의 build가 돌도록!
아래 링크를 들어가서 보면 쉽게 이해할 수 있을듯!

https://github.com/woowacourse-teams/2021-gpu-is-mine/actions/runs/1062490025
https://github.com/woowacourse-teams/2021-gpu-is-mine/actions/runs/1062490024

2021-07-24 12:50 UTC, bigsaigon333 approved these changes
그냥 궁금증 하나 남겼어요~!

---

그리고 저도 궁극적으로 하나로 통합되는게 좋을거 같아요

1. changes 로직이 동일하니까 두 번 할 필요가 없고,

2. job 별로 다 status checks 가 뜨니까 FE build 인지 BE build 인지 구별이 잘 될 것 같아요

3. workflow 에서 FE, BE build 되는게 시각적으로 통합적으로 잘 보일듯 :+1: 

아래의 그림은 제가 생각한 통합했을때의 workflow 입니다. 

![image](https://user-images.githubusercontent.com/31029000/126868914-69d2b5c6-45dc-4e1e-8a8b-f7286ceb0556.png)

2021-07-24 12:50 UTC, bigsaigon333 commented on .github/workflows/backend.yaml
> +    runs-on: ubuntu-latest
실제 동작환경과 테스트 환경을 똑같이 하는게 좋을거 같다는 생각에 

EC2 인스턴스 생성할때 ubuntu 18.04 로 지정했던게 생각나서, front-end CI 할 때 ubuntu-18.04 로 저는 변경했었는데요

BE는 굳이 그럴 필요 없나요? 

(젠킨스가 도커안에서 돌아서 상관없다던지?   

도커는 OS 레벨단의 컨테이너가 아닌걸로 알고 있어서, 도커 자체도 18.04 위에서 돌아가는거 아닌가요? <-- 잘 몰라서 물어봅니당 ㅎㅎ)

2021-07-24 12:50 UTC, bigsaigon333 commented on .github/workflows/backend.yaml
>      runs-on: ubuntu-latest
https://github.com/woowacourse-teams/2021-gpu-is-mine/pull/160#discussion_r675995338

2021-07-24 12:50 UTC, bigsaigon333 commented on .github/workflows/backend.yaml
>      runs-on: ubuntu-latest
https://github.com/woowacourse-teams/2021-gpu-is-mine/pull/160#discussion_r675995338

2021-07-24 13:51 UTC, wannte commented on .github/workflows/backend.yaml
> +    runs-on: ubuntu-latest
젠킨스 도커의 os 버전에 맞춰주는게 맞겠네요!
그 부분을 확인하지 않고 진행했었네요..

사실 os 버전에 따라서 build자체가 안되고 되고 하지 않을거 같긴한데! 확인해보도록 하겠습니다!

2021-07-24 13:54 UTC, wannte commented
@bigsaigon333 
와 이게 job별로 표시가 되는 거였네요... 와..! 이번 commit에 통합 진행하는 건 어떻게 생각하시나용??

2021-07-24 14:58 UTC, bigsaigon333 commented
> @bigsaigon333
> 와 이게 job별로 표시가 되는 거였네요... 와..! 이번 commit에 통합 진행하는 건 어떻게 생각하시나용??

너무너무 좋습니다 :+1: 

이번에 통합으로 ㄱㄱ 하면 좋을거 같아요

2021-07-25 04:46 UTC, bigsaigon333 commented
변수명 확인완료했고 저는 만족합니다 :+1: 

branch 에서 status check required 하는거는 제가 설정 완료했어요
![image](https://user-images.githubusercontent.com/31029000/126888002-049a62a7-a287-43c6-a77d-0f15efbe917e.png)

---

BE workflow 관련 질문입니다!

순서가 BE_checkstyle -> BE_test -> BE_build 가 먼가 자연스러운 흐름인거 같은게 제 느낌적인 느낌인데 아닌가요?

뭔가 비용이 작고 코드레벨 체크인  checkstyle 을 먼저 해서 통과를 하면  test를 돌리고, test를 통과하면 build 를 하는게 

자연스러울것 같다는 느낌이 들어서 코멘트 남겨봅니다 :smile: 

![image](https://user-images.githubusercontent.com/31029000/126888055-58c0d0a3-8197-4549-a9e7-3047aa1b8897.png)

2021-07-25 04:48 UTC, bigsaigon333 requested changes
요거 2개만 수정해주세요~

2021-07-25 04:48 UTC, bigsaigon333 commented on .github/workflows/gpu-is-mine-CI.yml
> +    needs: [changes, FE-build]
```suggestion
    needs: FE-build
```

2021-07-25 04:48 UTC, bigsaigon333 commented on .github/workflows/gpu-is-mine-CI.yml
> +      working-directory: ${{ env.working-directory }}
```suggestion
      working-directory: ${{ env.working-directory }}
      
```

2021-07-25 06:35 UTC, sjpark-dev commented
> 순서가 BE_checkstyle -> BE_test -> BE_build 가 먼가 자연스러운 흐름인거 같은게 제 느낌적인 느낌인데 아닌가요?

동동 말대로 이 순서가 더 자연스러울 것 같아요!

2021-07-25 06:44 UTC, wannte commented
@bigsaigon333  @sjpark-dev 
back-end pipe-line 설명을 여기다 달겠습니다.

기존의 build가 시간이 오래 걸렸던 이유는 그 build 내부적으로 checkstyle 과 test 모두 진행이 되기 때문이였습니다.

-x option 으로 checkstyle과 test 모두 진행 안되게끔 설정을 진행해주어서, 말그대로 `build 자체가 안되는 상황 = 코드 자체적인 에러` 를 검증하는 과정이라고 생각해주면 될 것 같아요! 실제로 시간도 거의 소요되지 않구요!

그래서 build -> checkstyle -> test 순으로 진행한느 것으로 개인적으로 결정하였습니다. 

아래 [jenkins docs pipeline](https://www.jenkins.io/doc/book/pipeline/)에서 이미지를 발췌해 왔습니다. 여기서도 test를 진행하기 전 build 를 진행을 하고 있습니다. 

> back-end 분들은 build.gradle에서 코끼리 누르는 게 build 단계라고 생각하시면 좋을 것 같아요!

![realworld-pipeline-flow](https://user-images.githubusercontent.com/49307266/126890230-a632b376-2880-43df-91aa-382fecca4ff0.png)

2021-07-25 06:50 UTC, sjpark-dev commented
> 기존의 build가 시간이 오래 걸렸던 이유는 그 build 내부적으로 checkstyle 과 test 모두 진행이 되기 때문이였습니다.
> 
> -x option 으로 checkstyle과 test 모두 진행 안되게끔 설정을 진행해주어서, 말그대로 `build 자체가 안되는 상황 = 코드 자체적인 에러` 를 검증하는 과정이라고 생각해주면 될 것 같아요! 실제로 시간도 거의 소요되지 않구요!
> 
> 그래서 build -> checkstyle -> test 순으로 진행한느 것으로 개인적으로 결정하였습니다.

설명 감사합니다!
그렇다면 완태가 정한 순서가 좋겠네요. 👍

2021-07-25 06:55 UTC, bigsaigon333 approved these changes
고생하셨습니다 :+1:

2021-07-25 07:01 UTC, merged