feat: 대기 중인 job 취소 기능 추가
woowacourse-teams/2021-gpu-is-mine pull request #242
Opened 2021-08-04 06:34 UTC by 2SOOY

close #241

2021-08-04 06:36 UTC, 2SOOY commented on front-end/src/hooks/useApi/useApi.ts
> +    relatedKey: [API_ENDPOINT.LABS(labId).JOBS, API_ENDPOINT.LABS(labId).GPUS],
Job 등록시 서버를 선택하고 해당 column에 잔여 시간이 존재합니다.
때문에 Job이 성공적으로 등록 시 GPU 서버 중 `잔여 시간`에 해당하는 항목의 column을 업데이트 하기 위해서 추가한 항목입니다.

2021-08-04 07:31 UTC, bigsaigon333 requested changes
고생 많으셨습니다~ :+1: 

코멘트 확인 부탁드려요!

2021-08-04 07:31 UTC, bigsaigon333 commented on front-end/src/domains/GpuServerSelectItem/GpuServerSelectItem.tsx
> +  const remainingTime = jobs.reduce((total, job) => total + Number(job.expectedTime), 0);
`Number(job.expectedTime)` 가 `NaN`이 될 경우에 `remainingTime` 이  `NaN`이 될 수도 있을 거 같아요

`Number(job.expectedTime)`이 `NaN`이면 `0`으로 한다던지... 하는 예외처리가 필요할 거 같아요

2021-08-04 07:31 UTC, bigsaigon333 commented on front-end/src/domains/JobInfoItem/JobInfoItem.tsx
>    };
```suggestion
  const handleDetailClick = useMoveToPage(`${PATH.MANAGER.JOB.VIEW}/${jobId}`);
```

2021-08-04 07:31 UTC, bigsaigon333 commented on front-end/src/domains/JobInfoList/JobInfoList.tsx
> +              .map((res) => <JobInfoItem key={res.id} refresh={() => makeRequest()} {...res} />)
`refresh={() => makeRequest()}` 로 바꾼 이유가 궁금합니다!

2021-08-04 07:31 UTC, bigsaigon333 commented on front-end/src/domains/JobInfoItem/JobInfoItem.tsx
>    const { myInfo } = useAuth() as { myInfo: MyInfoResponse };
```suggestion
  const labId = useLabId();
```

또는 page에서 `uselabId`를 호출해서 `labId`를 가져온 다음에, prop drilling으로 `labId`를 가지고 와도 좋을거 같아요. 
`labId`가 `null`인 경우는 정상적인 상황이 아니므로, page초기 진입시에 error를 터뜨리는게 좋지 않을까요

2021-08-04 07:31 UTC, bigsaigon333 commented on front-end/src/domains/GpuServerSelectItem/GpuServerSelectItem.tsx
> +  const remainingTime = jobs.reduce((total, job) => total + Number(job.expectedTime), 0);
expectedTime의 타입이 string이 맞나요? 만약 그렇다면 Number로 해달라고 BE랑 논의를 해야할 거 같기도 하네요

2021-08-04 08:17 UTC, 2SOOY commented on front-end/src/domains/JobInfoList/JobInfoList.tsx
> +              .map((res) => <JobInfoItem key={res.id} refresh={() => makeRequest()} {...res} />)
**결론부터 말하자면 `TypeError` 때문입니다.**


`makeRequest`의 type을 살펴보면 다음과 같습니다.
```ts
(body: void) => Promise<MakeRequestReturnType<JobViewResponses>>
```

`makeRequest`를 가공 없이 그대로 넣어주게 된다면 `<Alert onConfirm={makeRequest} />`에 형태로 사용됩니다,
이때, `onConfirm`은 `MouseEventHandler`라서 다음과 같은 타입을 갖습니다
```ts
(event: MouseEvent) => void
```
결과적으로 가공없이 makeRequest함수를 사용한다면 `body에 event객체`가 들어가서 error가 나는 것을 확인할 수 있습니다. 근데 저는 처음보는 에러네용,,
![image](https://user-images.githubusercontent.com/46412689/128146208-55ff2f52-6a5b-4d81-a9c0-d2a9bb7a5297.png)

--- 
이 부분은 `동동`이 이전 캐시 [PR](https://github.com/woowacourse-teams/2021-gpu-is-mine/pull/236)(`front-end/src/domains/GpuServerInfoList/GpuServerInfoList.tsx`)에서 참고했습니다 :) 덕분에 일찍 해결할 수 있었습니당 👍👍👍

2021-08-04 11:20 UTC, 2SOOY commented on front-end/src/domains/JobInfoItem/JobInfoItem.tsx
>    const { myInfo } = useAuth() as { myInfo: MyInfoResponse };
a2ca2da

나머지 컴포넌트에서 `labId=1` 형태로 fix했기 때문에 **우선** 동일한 방식으로 변경했습니다.
이 부분은 아마 동동이 `useAuth`관련 해서 해결해줬기 때문에 **추후에 `useLabId`를 사용해도 괜찮을 것 같습니다.**

2021-08-04 11:25 UTC, 2SOOY commented on front-end/src/domains/JobInfoItem/JobInfoItem.tsx
>    };
`PATH.MANAGER.JOB,VIEW/{jobId}`이 useMoveToPage에서 선언한 인자 타입과 맞지 않습니다.
따라서 실질적으로 사용하는 함수가 `history.push`이기 때문에 push의 인자 타입인 To를 불러왔긴 했지만, eslint가 경고를 띄어서 좋은 방법인지는 모르겠네요,,
```ts
// node_modules/history/index.d.ts

export declare type To = string | PartialPath;
/**
 * A history is an interface to the navigation stack. The history serves as the
 * source of truth for the current location, as well as provides a set of
 * methods that may be used to change it.
 *
 * It is similar to the DOM's `window.history` object, but with a smaller, more
 * focused API.
 */


push(to: To, state?: S): void;
    /**
     * Replaces the current location in the history stack with a new one.  The
     * location that was replaced will no longer be available.
     *
     * @param to - The new URL
     * @param state - Data to associate with the new location
```

2021-08-04 11:27 UTC, 2SOOY commented on front-end/src/domains/GpuServerSelectItem/GpuServerSelectItem.tsx
> +  const remainingTime = jobs.reduce((total, job) => total + Number(job.expectedTime), 0);
2cd65cc

처음부터 Number 타입으로 받으면 별도의 처리도 필요없겠군용
우선은 NaN 처리 진행하였습니다

2021-08-05 02:32 UTC, bigsaigon333 commented on front-end/src/domains/JobInfoItem/JobInfoItem.tsx
>    };
type string 사용 및 matchPath 로 path 확인하는 것으로 :+1:

2021-08-05 02:40 UTC, bigsaigon333 commented on front-end/src/domains/JobInfoItem/JobInfoItem.tsx
>    const { myInfo } = useAuth() as { myInfo: MyInfoResponse };
일부 페이지는  `labId`를 내려주고 있을거에요
한번에 다 처리하기 귀찮아서, 눈에 보일 때마다 처리하고 있습니다
다음에는 일관성 생각하지 말고 그냥 눈에 보이는건 바로 리팩토링 해주세요 :+1:

2021-08-05 02:40 UTC, bigsaigon333 approved these changes

2021-08-05 04:08 UTC, merged