feat: Table 컴포넌트 구현
woowacourse-teams/2021-gpu-is-mine pull request #270
Opened 2021-08-08 00:49 UTC by 2SOOY

정말 늦었네요ㅜ
아직 기본적인 sort기능 밖에 넣지 못했습니다
우선 현재까지 확인 부탁드려용

계속해서 Job 상세 테이블 작업 진행하도록 하겠습니다

2021-08-08 05:47 UTC, bigsaigon333 requested changes
코멘트 남겼습니다~~
 
테이블 컴포넌트를 보니 흐뭇하네요 :+1: 
 
UI 적으로는, 상세 버튼이 있는 row 만 height가 달라서 정렬시 row 가 흔들리는 느낌이 나긴 하는데...
 
뭐 상관없으려나요 ㅎㅎ (엑셀을 상상해보니 각 row마다 height를 다르게 지정할 수 있네요 ㅎㅎ)
 
 
![image](https://user-images.githubusercontent.com/31029000/128622156-f4e43fbd-53de-4455-b2bf-a87e6e85b2bc.png)

2021-08-08 05:47 UTC, bigsaigon333 commented on front-end/src/components/Table/Table.tsx
> +    }
a[field] 가 "" 또는 0 인 경우에도 !a[field] 가 true가 되어버리는데, 이게 의도하신 바가 맞나요?

2021-08-08 05:47 UTC, bigsaigon333 commented on front-end/src/components/Table/Table.tsx
> +// TODO: <HELP> lint 에러 고치느라 타입가드를 해줬는데도 적용이 안돼서 as 사용
```
  rows.slice().sort((a, b) => {
      const valueA = a[field];
      const valueB = b[field];
```
위와 같이 valueA, valueB 로 값을 선언, 할당해두고 타입 좁히기를 하면 타입 단언을 안해도 되는 거 같아요

2021-08-08 05:47 UTC, bigsaigon333 commented on front-end/src/components/Table/Table.tsx
> +// 해당 sort 함수의 위치? 여기 or util로 분리
저는 아무데나 상관없다고 생각합니다 편하신대로 :+1:

2021-08-08 05:47 UTC, bigsaigon333 commented on front-end/src/components/Table/Table.styled.ts
> +    transition: text-decoration 0.5s ease-in-out;
이건 왜 있는걸까요..? 
text-decoration 속성이 지정이 안되어 있는데, 뭔가가 빠진걸까요?

2021-08-08 05:47 UTC, bigsaigon333 commented on front-end/src/components/Table/Table.tsx
> +          <StyledRow key={rowIndex}>
이러한 경우에는 key로 index를 사용하면 안되지 않나요?

동일한 요소가 순서만 바뀌는 경우에 array index를 key를 사용하면 동일한 key에 다른 요소가 할당되므로

계속해서 새로운 ReactNode를 생성하게 되어 성능상 비효율이 발생하는 거 같아요

각 row에 대한 유일한 값을 key로 지정해주는게 좋을것 같아요

(유일한 값을 어떻게 구할지는 구체적인 방법이 생각나진 않네요.. 고민좀 해봐야 할 거 같아요)

2021-08-08 05:47 UTC, bigsaigon333 commented on front-end/src/components/Table/Table.tsx
> +const sortRowsByField = (rows: Row[], field: string, order: Order) =>
테스트 작성에 도전해보시는 걸 추천드립니다 :+1:

2021-08-08 08:35 UTC, 2SOOY commented on front-end/src/components/Table/type.ts
> +export type Row = Record<string, string | number | null | ReactNode>;
6753974

그렇네요 실제로 value값도 `ReactNode`로 추론되네용 :)

2021-08-08 08:36 UTC, 2SOOY commented on front-end/src/hooks/useTable/useTable.ts
> +type Order = "asc" | "desc";
baabc69

타입 위치 옮기는 것과 함께 반영했습니다 :)

2021-08-08 08:36 UTC, 2SOOY commented on front-end/src/components/Table/type.ts
> +}
baabc69 

넵 :) 옮기는 게 좋겠어용

2021-08-08 08:39 UTC, 2SOOY commented on front-end/src/components/Table/Table.tsx
> +    }
53e90a9

0인 경우에 대해는 생각을 하지 않았네요ㅜ

값이 존재하지 않거나, 빈 값일 경우 정렬 시 마지막으로 빼는 게 좋다고 생각해서 다음과 같이 작성했는데,
`0`의 경우 정렬에서 의미가 있는 값이니깐 해당 케이스에 포함되면 안되겠네요,,

`null | undefined | ''`인지 확인하도록 변경하였습니다.

2021-08-08 08:40 UTC, 2SOOY commented on front-end/src/components/Table/Table.tsx
> +// TODO: <HELP> lint 에러 고치느라 타입가드를 해줬는데도 적용이 안돼서 as 사용
53e90a9

오 그런 방법이 있었군요 👍👍👍 역시 동동 감사합니다 🙏

2021-08-08 08:41 UTC, 2SOOY commented on front-end/src/components/Table/Table.tsx
> +// 해당 sort 함수의 위치? 여기 or util로 분리
제거했습니당 :)

2021-08-08 08:41 UTC, 2SOOY commented on front-end/src/components/Table/Table.styled.ts
> +    transition: text-decoration 0.5s ease-in-out;
이것저것 해보다가 지우지 못했네용,, 이 부분도 제거하였습니다.

2021-08-08 08:43 UTC, 2SOOY commented on front-end/src/components/Table/Table.tsx
> +const sortRowsByField = (rows: Row[], field: string, order: Order) =>
테스트 작성해야겠다는 생각이 들긴 했는데, 시간이 너무 오래 소요될까봐
우선 JOB 상세 조회 테이블이 완성되면 작성해보도록 하겠습니다. (테스트 작성시 HELP 하겠습니다 ㅎㅎ)

2021-08-08 08:46 UTC, 2SOOY commented on front-end/src/components/Table/Table.tsx
> +          <StyledRow key={rowIndex}>
우선 Row에 대한 타입을 다음과 같이 변경하였습니다.

```ts
// 변경 전
type Row = Record<string, ReactNode>

// 변경 후
type Row = {
  id: number,
  data: Record<string, ReactNode>
}

```

보통 API요청 시 각 데이터에 대한 id를 받을 수 있으니깐 대응할 수 있다는 생각이 드네요,
혹시 id값이 없다면 사용 측에서 id값을 생성해서 넣는 방식으로 구현해야겠네요

+ **`TODO`: response 에 대하여 Row 타입 처럼 만들어 주는 유틸 함수 필요할 듯**

2021-08-09 05:19 UTC, bigsaigon333 approved these changes
코멘트 확인했씁니다  고생하셨습니다 :+1:

2021-08-09 05:23 UTC, merged