feat: GPU 서버 및 JOB 상세 조회 페이지 스타일 개선
woowacourse-teams/2021-gpu-is-mine pull request #449
Opened 2021-10-20 08:12 UTC by 2SOOY

close #450
close #454 

### 변경 전
![image](https://user-images.githubusercontent.com/46412689/138052931-96483f8b-addb-4158-8ac1-86f5307bdcc0.png)
![image](https://user-images.githubusercontent.com/46412689/138053066-a0313b80-7a1f-422b-86c4-712ed48d4e4c.png)
![image](https://user-images.githubusercontent.com/46412689/138053172-4de4422a-e544-46a9-91fe-678d7a000fe7.png)

---

### 변경 후
![image](https://user-images.githubusercontent.com/46412689/138053387-d5548596-73c2-4d5c-b95f-526531fe0265.png)
![image](https://user-images.githubusercontent.com/46412689/138053775-50388500-06b1-4059-8109-46e2c8c79f0d.png)
![image](https://user-images.githubusercontent.com/46412689/138053807-13359e88-1f66-436d-beb9-a9d270b94ad2.png)

2021-10-20 14:58 UTC, bigsaigon333 requested changes
고생하셨습니다 콜린~~

별도 이슈로 빼야할지, 여기서 바로 해도 좋을지 몰겠지만... 일단 눈에 보이는 사항 몇개 남겨봅니다 :smile: 

## 1. Job 목록에 Job이 하나도 존재하지 않는 경우
![image](https://user-images.githubusercontent.com/31029000/138117628-3ec631e7-c63f-4d42-a9ae-17c85cfef366.png)

(1) `Job이 존재하지 않습니다. ` 같은 문구를 표시하면 어떨까요?
(2) 오른쪽 밑에 Pagination에 `1/0` 문구 수정과 활성화되어 있는 `>` `>>` 도 비활성화시키면 좋을거 같아요 

## 2. Log 문구랑 콘솔창 사이에 간격 추가
![image](https://user-images.githubusercontent.com/31029000/138117696-8278ac96-2db9-464a-af5b-46684249aee7.png)

전에 코기가 남겨줬던 사항인거 같은데, Log 문구랑 남색바탕 콘솔창 사이에 마진을 좀더 주면 좋을거 같아요 :+1:

2021-10-20 14:58 UTC, bigsaigon333 commented on front-end/src/domains/GpuServerDetail/GpuServerDetail.tsx
> +          {jobId ? (
`jobId` 가  `0`이어도                 `현재 실행 중인 Job이 없습니다` 가 보여지지 않을까요? :eyes:

2021-10-20 14:58 UTC, bigsaigon333 commented on front-end/src/domains/JobDetailSummary/JobDetailSummary.tsx
> +            <Text as="dd">{detail.name}</Text>{" "}
```suggestion
            <Text as="dd">{detail.name}</Text>
```

2021-10-21 22:20 UTC, 2SOOY commented on front-end/src/domains/GpuServerDetail/GpuServerDetail.tsx
> +          {jobId ? (
e26f58d

2021-10-21 22:28 UTC, 2SOOY commented
> ### 1. Job 목록에 Job이 하나도 존재하지 않는 경우
> (1) `Job이 존재하지 않습니다. ` 같은 문구를 표시하면 어떨까요? (2) 오른쪽 밑에 Pagination에 `1/0` 문구 수정과 활성화되어 있는 `>` `>>` 도 비활성화시키면 좋을거 같아요

+ 빈 Job 목록에 대한 JobTable 처리 : 5f5b04d
+ 데이터 없을 때, 페이지네이션 처리 : 62d2b88

> ### 2. Log 문구랑 콘솔창 사이에 간격 추가
> 전에 코기가 남겨줬던 사항인거 같은데, Log 문구랑 남색바탕 콘솔창 사이에 마진을 좀더 주면 좋을거 같아요 👍

+ 문구와 콘솔창 사이의 마진 추가 : df0e676

추가로 gpu서버 상세 조회 및 job상세 조회 페이지에서 Job 요약 정보를 보여주는 컴포넌트도 공통적인 부분을 추출해보았습니다 :) 235ad43

---

### 로그 컨테이너 마진
![image](https://user-images.githubusercontent.com/46412689/138365429-c9ec7347-a40c-4f6c-bd41-87f28732fa9a.png)


### 현재 실행 중인 Job, Job 목록 없을 때 
![image](https://user-images.githubusercontent.com/46412689/138365285-f3308465-6519-4ff1-b8f5-3df05e94a04c.png)

2021-10-22 00:05 UTC, bigsaigon333 approved these changes
눈으로 보기에 확연히 차이가 나는 스타일 개선이네요 :+1: 

고생하셨습니다~~ 콜린 짱 :laughing:

2021-10-22 00:30 UTC, merged