feat: GpuServer CRUD 기본기능 구현
woowacourse-teams/2021-gpu-is-mine pull request #57
Opened 2021-07-10 01:33 UTC by knae11

Closes #30 

# 마무리 작업하면서 수정했던 사항
- 지금 생각나는 내용은 아래 항목들 정도네요. 😄
## Dto 관련
- 사용하지 않는 dto 제거
- 테스트시 필요한 기본생성자 및 getter 추가
## Controller 관련
- 전체조회시, soft 삭제 기능에 따라 findAll 메소드 대신 deleted = false 인 GpuServer 만 가져옴 
    - 기존에는 삭제여부와 상관없이 모든 것을 가져옴
- save 시, GpuBoard 도 DB에 저장되게 적용   
    - 기존에 추가시 Server 만 적용되고 Board는 적용되지 않았음
- Exception 핸들링 메소드 추가
    - 기존에 예외 핸들링 없었음
- ResponseEntity 적용되지 않았던 Controller에 반환값 ResponseEntity로 적용
    - 일부만 적용되었음 
- 프론트와 회의시, Void 리턴은 없이 값이 없더라도 `{}` 빈 제이슨 값을 보내주기로 한 내용 적용
    - 기존은 `ResponseEntity<Void>` 
## 범용적
- 메소드 이름 일부 수정

2021-07-10 02:31 UTC, sjpark-dev commented
ID로 특정 GPU서버를 조회할 때 soft 삭제된 서버까지 조회되는 버그를 수정했습니다!

2021-07-10 03:01 UTC, wannte requested changes
정말 수고하셨습니다..!
테스트까지 완벽하게 짜주셨네요!

테스트에 관한 제 생각을 한번 적어봤어요.

확인하시구 재요청 주세요!

2021-07-10 03:03 UTC, wannte commented on back-end/src/test/java/admin/gpuserver/ui/GpuServerAcceptanceTest.java
> +public class GpuServerAcceptanceTest extends AcceptanceTest {
저는 Request와 같은 객체들은 테스트 위에,
테스트 진행하는데 사용하는 메소드들은 테스트 밑에 두어 사용해요

2021-07-10 03:19 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/exception/GpuServerServiceException.java
> +@ResponseStatus(HttpStatus.BAD_REQUEST)
개발 단계에서 편의를 위해서 임시로 사용했습니다. 
실제로 이 방식은 에러 메세지를 보내주는 작업이 까다로워서 사용하지 않는 것이 좋습니다. (프로퍼티 파일의 설정을 바꿔야 합니다.)
말씀하신대로 ControllerAdvice에서 처리를 하니 `@ResponseStatus`는 삭제하곘습니다. 👍

2021-07-10 03:21 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/domain/DeleteHistory.java
> +public class DeleteHistory extends BaseEntity {
어떤 클래스의 삭제 이력인지 구체화하는 것도 좋겠지만,
나중에 GPU board, Lab, LabUser등도 DeleteHistory에 추가될 수 있기에 남기는게 좋을 것 같습니다!

2021-07-10 03:30 UTC, wannte commented on back-end/src/test/java/admin/gpuserver/ui/GpuServerAcceptanceTest.java
> +    }
이 부분은 전반적인 테스트에 걸쳐있는 생각이라, 각 테스트별로 추가로 작성하지는 않았습니다.

2021-07-10 06:28 UTC, sjpark-dev commented on back-end/src/test/java/admin/gpuserver/ui/GpuServerAcceptanceTest.java
> +    }
이 부분은 [이슈](https://github.com/woowacourse-teams/2021-gpu-is-mine/issues/60)로 분리 했습니다.

2021-07-10 06:29 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/domain/DeleteHistory.java
> +public class DeleteHistory extends BaseEntity {
이부분도 [이슈](https://github.com/woowacourse-teams/2021-gpu-is-mine/issues/58)로 분리 했습니다.

2021-07-10 06:33 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/ui/GpuServerController.java
> +                .body(gpuServerResponse);
저도 이 방식이 더 좋아 보여요 :)

2021-07-10 06:34 UTC, sjpark-dev commented on back-end/src/test/java/admin/gpuserver/ui/GpuServerAcceptanceTest.java
> +public class GpuServerAcceptanceTest extends AcceptanceTest {
저도 완태말에 동의합니다.
다른 분들은 어떤 의견을 가지고 있는지 궁금하네요!

2021-07-10 15:47 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +                gpuServerRequest.getMemorySize(),
gpuServer의 diskSize로 요청의 memorySize가 들어가는데 의도하신걸까요?

```
GpuServer gpuServer = new GpuServer(gpuServerRequest.getServerName(),
                gpuServerRequest.getMemorySize(),
                gpuServerRequest.getMemorySize(), lab);
```

2021-07-10 16:03 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/dto/response/GpuResponses.java
> +public class GpuResponses {
DTO 명이 불분명하다고 생각합니다.
List<GpuServerResponse> 의 변수명으로 GpuBoardRespons를 의도한 것이 맞는지요.
GpuResponses가 담는 정보가 GpuServerResponse의 리스트인가요, GpuBoardResponse의 리스트인가요?

```
public class GpuResponses {
    List<GpuServerResponse> gpuBoardRespons;

    public GpuResponses(List<GpuServerResponse> gpuBoardRespons) {
        this.gpuBoardRespons = gpuBoardRespons;
    }

    public List<GpuServerResponse> getGpuResponses() {
        return gpuBoardRespons;
    }
}
```

2021-07-10 16:05 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/dto/response/GpuBoardResponse.java
> +    private Boolean isWorking;
DTO에 Boolean으로 Wrapper를 쓴 이유가 있을까요?

수정 요구가 아닌, 의도하신건가 궁금합니다.

2021-07-10 16:09 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/dto/response/EmptyJsonResponse.java
> +    public EmptyJsonResponse() {
이렇게 기본 생성자 명시가 필요한가요?
신기하네요!!
빈 생성자를 안만들어주는가요..?

2021-07-10 16:13 UTC, ecsimsw commented on back-end/src/test/java/admin/gpuserver/domain/repository/DeleteHistoryRepositoryTest.java
> +        GpuServer gpuServer = gpuServerRepository.findById(1L).get();
이 테스트, 테스트 클래스가 어떤 의미인지 모르겠습니다.
덜 지운건가요?

2021-07-10 16:25 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +        labValidation(labId);
gpuServer delete에서 lab 정보가 필요할까요?

2021-07-10 16:48 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +        Lab lab = labRepository.findById(labId).get();
labRepository.findById으로 lab 존재 여부를 확인하고 다시 findById 하는 꼴이 괜찮을까요?

```
public Long saveGpuServer(GpuServerRequest gpuServerRequest, Long labId) {
         labValidation(labId);
         Lab lab = labRepository.findById(labId).get();

private void labValidation(Long labId) {
    labRepository.findById(labId)
            .orElseThrow(() -> new GpuServerServiceException("Lab이 존재하지 않습니다."));
}
```

labValidation을 빠트리면 get()이 노출돼서 바로 터지는 꼴인데, 아래의 꼴은 어떠세요?

```
public Long saveGpuServer(GpuServerRequest gpuServerRequest, Long labId) {
         Lab lab = labRepository.findById(labId).orElseThrow(() -> new GpuServerServiceException("Lab이 존재하지 않습니다."));
```

2021-07-10 17:01 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +    public GpuServerResponse findById(Long labId, Long gpuServerId) {
GpuServer의 findById가 정말 id로 GpuServer를 가져오는 것이 아닌 '살아있는' GpuServer만을 가져오는군요!!

2021-07-10 17:06 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +    public GpuServerResponses findAll(Long labId) {
마찬가지로 findAll도 그냥 모든 GpuServer를 가져오는 것이 아닌, lab안의 살아있는 GpuServer만을 받아오네요!

저는 findById 가 살아있는 gpuServer만을 가져오는지, 상태와 상관없이 id로 조회하는지
findAll이 Lab안의 살아있는 gpuServer를 가져오는지, 랩, 상태와 상관없이 모두 조회하는지

헷갈리는데 저만 그런가요? 다들 findById는 살아있는 서버만, findAll은 랩실 안의 서버를, 이라는 게 당연한지 궁금하네요.



```
@Transactional(readOnly = true)
public GpuServerResponses findAll(Long labId) {
    labValidation(labId);
    List<GpuServer> gpuServers = gpuServerRepository.findAllByDeletedFalse();
    return new GpuServerResponses(gpuServers);
}
```

2021-07-10 17:11 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +    private GpuServer findValidationGpuServer(Long gpuServerId) {
변수명이나 스타일에는 특별한 코멘트를 드리고 싶지 않았는데,

findValidationGpuServer, labValidation이 문법적으로 맞는지 궁금합니다.
유효한 서버를 찾는다. 라면 findValidGpuServer
랩을 검증한다. 라면 validateLab 

가 맞을거 같은데, 제가 영어를 잘못해서...

2021-07-10 17:16 UTC, ecsimsw commented on back-end/src/test/java/admin/gpuserver/application/GpuServerServiceTest.java
> +        GpuServerResponse gpuServer = gpuServerService.findById(1L, 1L);
Test 코드가 data.sql에 의존적이군요!!

gpuServerService.findById(1L, 1L); 
gpuServerService.findById(2L, 1L);
gpuServerService.findById(1L, 3L))

에서 앞의 Long, 뒤의 Long은 뭔지, 저장된 값인지 아닌지, 이 코드 내에선 전혀 확인할 수 없네요.

2021-07-10 17:19 UTC, ecsimsw commented on back-end/src/test/java/admin/gpuserver/application/GpuServerServiceTest.java
> +        assertThat(gpuServers.getGpus()).hasSize(1);
delete하고 getGpus() 한 원소의 개수가 1개면 삭제된 서버를 제외한 전체 조회가 확인되는 건가요?

이전에는 n개였고, 삭제 후 n-1개가 확인되어야 하는 것 같습니다.
기존에 2개가 있었는지, 1000개가 있었는지 알 수 없는 상황에서 해당 코드만 보고 테스트 확신을 갖을 수 없네요.

2021-07-10 17:22 UTC, ecsimsw commented on back-end/src/test/java/admin/gpuserver/application/GpuServerServiceTest.java
> +    @DisplayName("저장된 서버를 확인한다")
저희 엔티티 검증, DB 스케마 설정을 다시 확인해야할 것 같아요!!
아래 코드는 통과합니다.

```
// gpuServers : GpuServerRepository
// gpuBoards : GpuBoardRepository

@DisplayName("Gpu를 DB에 저장한다. _ 현재 통과")
@Test
void save_null() {
    Lab lab = null;
    GpuServer gpuServer = new GpuServer("새로운GPU서버1", false, -1L, -1L, lab);
    GpuBoard gpuBoard = new GpuBoard(true, 1000L, "aab", gpuServer);
    gpuServer.setGpuBoard(gpuBoard);

    gpuServers.save(gpuServer);
    gpuBoards.save(gpuBoard);
}
```

2021-07-10 17:36 UTC, ecsimsw reviewed
우선 정말 고생했습니다. 짧은 시간에 코드량이 엄청나네요!!! 
정말 수고하셨습니다. 대단하십니다.

가능하면 코드 스타일, 포맷팅은 건들이지 않고 리뷰했습니다.
다들 본인이 생각하는 스타일이 있으니...
다만, 코드 안에 연속된 빈 줄 같은, 자잘한 실수가 있긴 한데 그런 자잘한 것은 merge 후에도 변경이 안되는 경우 제가 작업할 때 슬쩍 고쳐 두겠습니다.

열심히 테스트 했는데 커멘트 외 다른 문제는 못 찾았습니다.
QA아닌 QA를 하면서 오히려 제 파트인, GpuServer, Jobs이 양방향 매핑 부분 CRUD에서 작성에서 주의깊게 테스트 할 곳을 미리 경험한 것 같습니다.

고생하셨습니다. 커멘트 확인하시고 답변 부탁드리겠습니다.

2021-07-10 17:43 UTC, ecsimsw commented on back-end/src/test/java/admin/gpuserver/ui/GpuServerAcceptanceTest.java
> +@DisplayName("GpuServer 관련 API 테스트 - labId: 1")
labId : 1

data.sql에 의존적인 테스트인 점이 걸리네요.
요청 path도 전부 매직 스트링이고
data.sql을 안쓰거나, labId가 변경되는 순간 못쓰는 코드

"/api/labs/1/gpus"

2021-07-10 17:43 UTC, ecsimsw commented
우선 정말 고생했습니다. 짧은 시간에 코드량이 엄청나네요!!!
정말 수고하셨습니다. 대단하십니다.

가능하면 코드 스타일, 포맷팅은 건들이지 않고 리뷰했습니다.
다들 본인이 생각하는 스타일이 있으니...
다만, 코드 안에 연속된 빈 줄 같은, 자잘한 실수가 있긴 한데 그런 자잘한 것은 merge 후에도 변경이 안되는 경우 제가 작업할 때 슬쩍 고쳐 두겠습니다.

열심히 테스트 했는데 커멘트 외 다른 문제는 못 찾았습니다.
QA아닌 QA를 하면서 오히려 제 파트인, GpuServer, Jobs이 양방향 매핑 부분 CRUD에서 작성에서 주의깊게 테스트 할 곳을 미리 경험한 것 같습니다.

고생하셨습니다. 커멘트 확인하시고 답변 부탁드리겠습니다.

2021-07-12 02:26 UTC, knae11 commented on back-end/src/main/java/admin/gpuserver/ui/GpuServerController.java
> +                .body(new EmptyJsonResponse());
NO_CONTENT 응답코드를 내보내려고 하는데 이 경우에는 body를 담을 수 없어서 해당 내용처럼 안 되더라구요! 프론트와 다시 논의를 하거나 다른 방안을 찾아봐야 할 듯 하네요 :)

2021-07-12 02:27 UTC, knae11 commented on back-end/src/main/java/admin/gpuserver/exception/GpuServerServiceException.java
> +@ResponseStatus(HttpStatus.BAD_REQUEST)
다른 팀원들도 해당 내용 볼 수 있게 conversation resolve는 하지 않는게 좋을 것 같은데 어떻게 생각하시나요?

2021-07-12 02:28 UTC, knae11 commented on back-end/src/main/java/admin/gpuserver/ui/GpuServerController.java
> +                .body(gpuServerResponse);
위에 no_content 와 통일하려고, 혹은 응답코드와 body를 분리해 주려고 의도한 것인데 이런 의견에 대해서는 어떻게 생각하시나요?

2021-07-12 02:28 UTC, knae11 commented on back-end/src/test/java/admin/gpuserver/ui/GpuServerAcceptanceTest.java
> +public class GpuServerAcceptanceTest extends AcceptanceTest {
저는 크게 상관 없네요 :) 맞춰지는 컨벤션에 따를게요!

2021-07-12 02:29 UTC, knae11 commented on back-end/src/test/java/admin/gpuserver/ui/GpuServerAcceptanceTest.java
> +                .then().log().all()
저는 개인적으로 완성된 프로젝트가 아니기 때문에 추후 확인을 위해서도 혹은 누군가가 놓친 테스트를 확인하기 위해서라도 `.log().all()` 이 있으면 좋겠다는 생각입니다. 다른 분들의 의견은 어떤지 궁금하네요 :)

2021-07-12 02:31 UTC, knae11 commented on back-end/src/test/java/admin/gpuserver/ui/GpuServerAcceptanceTest.java
> +    }
지금 도메인이 자리잡지 못한 상태에서는 단순히 쉽고, 빠르게 작성되고 실행되는 테스트가 좋아보입니다. 

변경될 가능성이 아직 충분히 많은 도메인 코드인데 리팩토링 때마다 테스트 내용을 변경하면 다소 번거로울 수 있어 보입니다. 따라서 현재로써는 데이터를 넣어두고 테스트하는 것이 편리하다는 생각입니다. :)

2021-07-12 03:34 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/exception/GpuServerServiceException.java
> +@ResponseStatus(HttpStatus.BAD_REQUEST)
좋습니다! unresolve 하겠습니다.

2021-07-12 09:37 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +    public GpuServerResponse findById(Long labId, Long gpuServerId) {
이 부분 넘기셔도 됩니다.

2021-07-12 09:38 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +        Lab lab = labRepository.findById(labId).get();
이 부분 넘기셔도 됩니다.

2021-07-12 09:38 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +    public GpuServerResponses findAll(Long labId) {
이 부분 넘기셔도 됩니다.

2021-07-12 10:46 UTC, knae11 commented on back-end/src/main/java/admin/gpuserver/ui/GpuServerController.java
> +                .body(new EmptyJsonResponse());
협의 결과
- status code는 204 no_content 를 유지하는 것이 맞다고 판단
- 다만 body를 넘겨주는 이유는 프론트와의 때문이다.
- 그래서 약간 부자연스럽더라도 지금의 방식을 가져가는 게 좋다고 판단.

2021-07-12 10:48 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/ui/GpuServerController.java
> +                .body(gpuServerResponse);
Response.ok(body) 로 통일했습니다.

2021-07-12 10:50 UTC, sjpark-dev commented on back-end/src/test/java/admin/gpuserver/ui/GpuServerAcceptanceTest.java
> +public class GpuServerAcceptanceTest extends AcceptanceTest {
테스트 메소드가 먼저 보이게 수정했습니다.

2021-07-12 10:50 UTC, MyaGya commented on back-end/src/test/java/admin/gpuserver/ui/GpuServerAcceptanceTest.java
> +                .then().log().all()
유지에 동의합니다

2021-07-12 10:52 UTC, sjpark-dev commented on back-end/src/test/java/admin/gpuserver/ui/GpuServerAcceptanceTest.java
> +                .then().log().all()
아직 서비스가 개발 완료 된 것이 아니라 나중에 로그를 참고할 수 있다고 생각합니다.
log().all()은 유지하겠습니다.

2021-07-12 10:57 UTC, sjpark-dev commented on back-end/src/test/java/admin/gpuserver/ui/GpuServerAcceptanceTest.java
> +        GpuBoardRequest gpuBoardRequest = new GpuBoardRequest("추가보드1", 800L);
Acceptance 메소드를 몇개 안되고 테스트 내에서  어떤 자원을 사용하는지 바보 보는게 좋을 것 같아서 유지하겠습니다.

2021-07-12 10:58 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +                gpuServerRequest.getMemorySize(),
수정했습니다.

2021-07-12 11:00 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/dto/response/GpuResponses.java
> +public class GpuResponses {
안쓰는 DTO였네요! 제거 했습니다.

2021-07-12 11:01 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/dto/response/GpuBoardResponse.java
> +    private Boolean isWorking;
Long을 wrapper 타입으로 쓰는 이유와 같습니다!

2021-07-12 11:01 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/dto/response/EmptyJsonResponse.java
> +    public EmptyJsonResponse() {
기본 생성자 제거했습니다.

2021-07-12 11:07 UTC, sjpark-dev commented on back-end/src/test/java/admin/gpuserver/domain/repository/DeleteHistoryRepositoryTest.java
> +        GpuServer gpuServer = gpuServerRepository.findById(1L).get();
지웠습니다!

2021-07-12 11:08 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +        labValidation(labId);
도메인 객체 설계 그대로 두기로 합의를 봤으므로 유지하겠습니다.

2021-07-12 11:16 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +        Lab lab = labRepository.findById(labId).get();
수정했습니다!

2021-07-12 11:17 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +    private GpuServer findValidationGpuServer(Long gpuServerId) {
수정했습니다!

2021-07-12 11:18 UTC, sjpark-dev commented on back-end/src/test/java/admin/gpuserver/application/GpuServerServiceTest.java
> +        assertThat(gpuServers.getGpus()).hasSize(1);
이슈로 남겼습니다.

2021-07-12 11:18 UTC, sjpark-dev commented on back-end/src/test/java/admin/gpuserver/application/GpuServerServiceTest.java
> +        GpuServerResponse gpuServer = gpuServerService.findById(1L, 1L);
이슈로 분리했으니 유지하겠습니다.

2021-07-12 11:19 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +    public GpuServerResponse findById(Long labId, Long gpuServerId) {
소프트 삭제한 것은 조회하지 않습니다.

2021-07-12 11:19 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +    public GpuServerResponses findAll(Long labId) {
소프트 삭제한 것은 조회하지 않습니다.

2021-07-12 11:22 UTC, sjpark-dev commented on back-end/src/test/java/admin/gpuserver/ui/GpuServerAcceptanceTest.java
> +@DisplayName("GpuServer 관련 API 테스트 - labId: 1")
이슈로 분리했으니 유지하겠습니다.

2021-07-12 11:24 UTC, MyaGya commented
피드백 변경 완료했습니다. 다시 확인 부탁드립니다.

2021-07-12 11:25 UTC, sjpark-dev commented on back-end/src/test/java/admin/gpuserver/application/GpuServerServiceTest.java
> +    @DisplayName("저장된 서버를 확인한다")
새 [이슈](https://github.com/woowacourse-teams/2021-gpu-is-mine/issues/66)로 남겼습니다.

2021-07-12 11:46 UTC, ecsimsw approved these changes
고생했다~~

2021-07-12 12:11 UTC, wannte commented on back-end/src/test/java/admin/gpuserver/ui/GpuServerAcceptanceTest.java
> +                .then().log().all()
혹시 log.all을 삭제하는 시점을 언제쯤으로 생각하시나요?

개발의 완료의 기준이, 전체 서비스의 완료 시점인지, 아니면 이 기능의 완료 시점인지가 궁금하네요.

개인적으로는 테스트를 실행하다 문제가 생겼을 때, 문제되는 테스트에서만 log.all을 작성하여 테스트를 검증해보는 것이 더 좋지 않을까 생각해요.

2021-07-12 12:15 UTC, wannte approved these changes
수코 수코~
Squash merge gogo~

2021-07-12 13:07 UTC, merged