feat: Confirm 컴포넌트 구현
woowacourse-teams/2021-gpu-is-mine pull request #74
Opened 2021-07-14 00:11 UTC by 2SOOY

+ Portal 컴포넌트 구현
+ Modal 컴포넌트 구현

modal을 재활용하여 confirm을 구현하려고 했으나,
modal을 활용하여 confirm을 구현하면 dimmed 영역을 클릭하면 confirm창이 닫히게 되어 별도의 컴포넌트로 구현했습니다 :)

![image](https://user-images.githubusercontent.com/46412689/125540845-018975e7-587e-4445-aa9e-90d77267b777.png)

2021-07-14 03:09 UTC, bigsaigon333 commented on front-end/src/components/Confirm/Confirm.styled.ts
> +  z-index: 70; // TODO: Confirm z-index
z-index 관리 어떻게 할까요? 
css 변수로 관리하는게 일관성 측면에서 좋을거 같은데, 

--z-index-confirm
--z-index-alert
--z-index-modal 
--z-index-base

뭐 이런식으로 할까요?

2021-07-14 07:53 UTC, bigsaigon333 requested changes
아직 다 못봤는데 본거까지만 1차로 리뷰 남깁니다!

2021-07-14 13:55 UTC, bigsaigon333 commented on front-end/src/components/Portal/Portal.tsx
> +  const $elem = document.createElement("div");
$ 삭제

2021-07-14 13:55 UTC, bigsaigon333 commented on front-end/src/components/Portal/Portal.tsx
> +  $elem.id = id ?? "portal";
id 할당 삭제

2021-07-15 03:26 UTC, bigsaigon333 commented on front-end/src/components/Modal/Modal.stories.tsx
> +    <div style={{ width: "200px", height: "100px", backgroundColor: "beige" }}>모달 내부 내용</div>
pass

2021-07-15 04:04 UTC, bigsaigon333 commented on front-end/src/components/Confirm/Confirm.tsx
> +            </Text>
children으로 변경

2021-07-15 04:04 UTC, bigsaigon333 commented on front-end/src/components/Confirm/Confirm.styled.ts
> +  z-index: 70; // TODO: Confirm z-index
#91

2021-07-15 04:05 UTC, bigsaigon333 approved these changes
수고수고~ :+1:

2021-07-15 04:05 UTC, 2SOOY commented on front-end/src/components/Confirm/Confirm.styled.ts
> +  z-index: 70; // TODO: Confirm z-index
`TODO` 
이슈 등록 z-index

2021-07-15 04:07 UTC, merged