feat: JOB 기능을 구현한다
woowacourse-teams/2021-gpu-is-mine pull request #86
Opened 2021-07-14 08:11 UTC by ecsimsw

Closes #36 
Closes #34
Closes #64

2021-07-14 09:35 UTC, wannte reviewed
우선 간단히 몇가지만 남길게요.
추후에 이어서 진행하겠습니다.

너무 많네요..

2021-07-14 09:35 UTC, wannte commented on back-end/src/main/java/admin/gpuserver/application/JobService.java
> +public class JobService {
job의 특성을 고려하여 save, delete 보다 insert, cancel 을 사용한 부분 good이라 생각합니다.

2021-07-14 09:35 UTC, wannte commented on back-end/src/main/java/admin/gpuserver/application/JobService.java
> +
서비스를 상속하고 싶다..
이 부분에 대해서는 마지막 합치는 과정에서 같이 고민해보죠

2021-07-14 09:35 UTC, wannte commented on back-end/src/main/java/admin/gpuserver/domain/GpuBoard.java
> +    }
job과 관련된 로직이 도메인에 들어가는 것이 어색하네요

Queue팀이 생각하는 부분은 queue서비스를 별도로 만들고 여기서 JobService에서 QueueService를 사용하는 그림으로 생각하는 듯 하네요

2021-07-14 09:35 UTC, wannte commented on back-end/src/test/java/admin/gpuserver/domain/GpuServerTest.java
> +                .hasMessage("객체를 생성할 수 없습니다.");
Java 11버전 이였으면, isBlank 를 사용하면 더 좋았을듯하네요

2021-07-14 09:35 UTC, wannte commented on back-end/src/test/java/admin/gpuserver/domain/GpuServerTest.java
> +    @ParameterizedTest
:+1:

2021-07-14 18:31 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/application/JobService.java
> +
오 저도 동의합니다.
다만 서비스 간 상하 관계가 뚜렷하지 않는다면 꼬일 수 있을 것 같다는 걱정도 됩니다.

안그래도 에드와 얘기 나왔던 부분인데 다른 팀원들과 날잡고 대화하고 싶어 일단 이렇게 두었습니다.

2021-07-14 18:39 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/domain/GpuBoard.java
> +    }
말씀대로 이 부분은 큐 팀과 대화하여 수정할 필요를 느꼈습니다.
사실 JobQueue의 위치가 GpuBoard 라고 가정하여, 오히려 job의 상태 변화를 GpuServerService가 관여하는게 맞을까를 고민했던 것 같습니다. 'Job을 GpuBoard에 넘기니 큐 처리 이후 Job 상태를 바로 변경해주자.' 라는 생각에 작성된 코드입니다.

해당 addJob, cancel, complete는 그 시그니처부터 크게 변경 또는 삭제될 것 같습니다.
꼼꼼한 리뷰 감사합니다.

2021-07-14 18:39 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/application/JobService.java
> +public class JobService {
👍👍👍

2021-07-14 18:41 UTC, ecsimsw commented on back-end/src/test/java/admin/gpuserver/domain/GpuServerTest.java
> +                .hasMessage("객체를 생성할 수 없습니다.");
자바 버전 변경을 고려하고 있습니다만, 이번 PR에서 너무 많은 변경이 있는 것 같아, 패키지 구조 변경을 포함한, 필요한 큰 변화를 진행하지 않았습니다.

2021-07-15 01:51 UTC, knae11 requested changes
도메인 설계하느라 고생했어요!!ㅎㅎㅎ
많이 바꾸느라 힘들었을 것 같아요ㅠㅠ
생성시점에 null과 관련해서 많은 테스트를 진행해주셨군요!!  👍 

- JobService가 있는데 Service 테스트는 진행하지 않은 이유가 있을까요?
- Job이 추가되었을때 리스트에 추가되서 나오는지 여부가 궁금하네요! 해당 내용에 대한 테스트가 보이지 않아서 아쉬웠어요!(혹시 제가 못 찾은 것이라면 알려주세요!)

2021-07-15 01:51 UTC, knae11 commented on back-end/src/main/java/admin/gpuserver/domain/BaseEntity.java
> +}
마지막에 개행라인 1줄을 추가하는 것을 컨벤션으로 가져가기로 했는데 해당내용이 반영되지 않은 것 같아요.
https://github.com/woowacourse-teams/2021-gpu-is-mine/pull/14#pullrequestreview-699262258

2021-07-15 01:51 UTC, knae11 commented on back-end/src/main/java/admin/gpuserver/domain/Job.java
> +    private LabUser labUser;
Job 을 조회할 때, 유저 정보가 맞는지 정도만 체크하게 될 것 같은데 id 참조로 하지 않고 객체 참조를 사용하신 이유가 있을까요?

2021-07-15 01:51 UTC, knae11 commented on back-end/src/main/java/admin/gpuserver/domain/DeleteHistory.java
> +    }
GpuServer의 객체를 생성할 수 없습니다 의 validate를 DeleteHistory에서 한다는 것이 약간 이상하게 느껴지네요. 객체를 생성하는 것은 GpuServer 자체의 일이라고 생각해서요!

2021-07-15 01:51 UTC, knae11 commented on back-end/src/test/java/admin/gpuserver/domain/DeleteHistoryTest.java
> +public class DeleteHistoryTest {
DeleteHistory 에 대해서 삭제될 시점에 진짜 History에 등록되는지 확인해주는 테스트가 있으면 좋을 것 같아요!

GpuServerTest 나 다른 테스트에 있을 것이라고 기대되는데 못찾아서 여기에 남길게요!ㅎㅎㅎ

2021-07-15 01:51 UTC, knae11 commented on back-end/src/main/java/admin/gpuserver/domain/Job.java
> +    public void setName(String name) {
왜 모든 항목에 대해 setter를 열어두신건가요?

2021-07-15 01:53 UTC, knae11 commented on back-end/src/main/java/admin/gpuserver/domain/Job.java
> +    public void cancel() {
상태가 잘 바뀌어 저장되는지에 대한 테스트도 있으면 좋을 것 같다는 생각이 들어요!

2021-07-15 01:59 UTC, wannte reviewed
몇가지 또 남겼습니다!

Job은 충분히 GpuServer로 부터 도메인 분리해도 좋을 것 같다는 생각입니다.!

2021-07-15 01:59 UTC, wannte commented on back-end/src/test/java/admin/gpuserver/application/GpuServerServiceTest.java
> +        assertThrows(GpuServerServiceException.class, () -> gpuServerService.delete(gpuServer1.getId()));
assertThrows 를 사용하는것도 깔끔하니 좋네요

2021-07-15 01:59 UTC, wannte commented on back-end/src/main/java/admin/gpuserver/domain/DeleteHistory.java
>  public class DeleteHistory extends BaseEntity {
Soft 삭제의 개념이 아직 와닿지 않아서 질문을 달아요!
GpuServer 객체가 삭제 여부를 boolean으로 가지고 관리를 하는 부분은 그 정보를 보관한다는 관점에서 이해가 되었는데,

이 삭제시점을 기록하는 deleteHistory의 경우 어떤 역할로 작용하는지 궁금해요!
GpuServer 객체와 deleteHistory db의 씽크를 맞춰야한다는 부담이 추가되기도 하고요

2021-07-15 01:59 UTC, wannte commented on back-end/src/main/java/admin/gpuserver/domain/GpuBoard.java
> +                || modelName == null || modelName.isEmpty() || gpuServer == null) {
모든 도메인의 유효성 검증을 진행해주셨네요  :+1: 

도메인에서 @Valid 어노테이션을 사용하기도 할까요? 그럼 편할거 같기도 하고

2021-07-15 01:59 UTC, wannte commented on back-end/src/main/java/admin/gpuserver/domain/GpuServer.java
> +            throw new GpuServerServiceException("객체를 생성할 수 없습니다.");
도메인에서 ServiceException을 터뜨리는 부분이 조금 어색한 것 같아요.

별도의 에러를 터뜨려서  사용하는 서비스에서 try catch로 잡아주고 ServiceException을 뿜어주는건 어떨까요?

다른 Service에서 GpuServer생성시 Exception이 떠져쓸 때도 GpuServerServiceException이 발생할 수 도 있겠네요

2021-07-15 01:59 UTC, wannte commented on back-end/src/test/java/admin/gpuserver/domain/GpuBoardTest.java
> +    }
```suggestion
    @DisplayName("생성 테스트 - 정상")
    @Test
    void 생성() {
        GpuBoard gpuBoard = new GpuBoard(false, 1000L, "모델1", gpuServer));
         assertThat(gpuBoard).isNotNull();
    }
```

실세로 생성이 되었는지를 확인해보는 것은 어떨까요?

에러가 나지 않는다 = 생성이 되었다 가 비슷하지만 동치는 아닐것 같은 개인적인 생각입니다.

2021-07-15 01:59 UTC, wannte commented on back-end/src/test/java/admin/gpuserver/ui/GpuServerAcceptanceTest.java
> +
AcceptanceTest에서 이미 선언되어서 제 선언할 필요 없을 것 같네요!

setup도 override 진행하고 super() 를 사용하는 것이 좋아보입니다.!

2021-07-15 02:22 UTC, MyaGya reviewed
몇 가지 제안을 추가했습니다

2021-07-15 02:22 UTC, MyaGya commented on back-end/src/main/java/admin/gpuserver/application/JobService.java
> +                .orElseThrow(() -> new IllegalArgumentException("board 가 없습니다."));
저도 메소드 안에는 핵심 로직만 있는 걸 선호합니다.

2021-07-15 02:22 UTC, MyaGya commented on back-end/src/main/java/admin/gpuserver/application/JobService.java
> +                .orElseThrow(() -> new IllegalArgumentException("job 이 없습니다."));
윗부분과 마찬가지에요, 핵심 로직만 남겨두고 예외처리에 관한 항목은 메소드로 빼는 방법은 어떨까요?

2021-07-15 02:22 UTC, MyaGya commented on back-end/src/main/java/admin/gpuserver/domain/GpuBoard.java
> +                || modelName == null || modelName.isEmpty() || gpuServer == null) {
@Valid 를 사용한 방법은 validate 코드를 따로 분리하여야 한다는 단점이 있어요. 도메인에서 처리하는 방법과 메소드로 따로 빼는 방법이 있기는 한데 어노테이션을 써서 하는 방법은 안 좋을 수 있다고 생각합니다. 도메인 안에 validate 코드가 직접적으로 들어가는 방법은 어떻게 생각하시나요?

2021-07-15 02:22 UTC, MyaGya commented on back-end/src/main/java/admin/gpuserver/domain/Job.java
>      }
객체 생성 불가능의 원인을 예외 메세지로 따로 구별해서 던져주는 건 어떻게 생각하시나요?

2021-07-15 02:22 UTC, MyaGya commented on back-end/src/test/java/admin/gpuserver/application/GpuServerServiceTest.java
> +    @DisplayName("존재하지 GPU_Server_ID로 GPU 서버의 이름을 수정한다.")
"존재하지" 로 시작하는 문장이 보이는데요
혹시 오타일까요?

2021-07-15 02:30 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/domain/BaseEntity.java
> +}
👍👍👍👍

2021-07-15 02:41 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/application/JobService.java
> +                .orElseThrow(() -> new IllegalArgumentException("board 가 없습니다."));
아래처럼 Repository에서 Optional을 반환받는 경우가 해당 클래스에 안에 다양하게 나오는데 모든 경우를 각각 메소드로 따로 빼는게 과연 가독성을 위한 것일까?라는 생각에서 그렇게 진행하였습니다.

이번 경우처럼 Service 로직에서 Optional을 다뤄야하는 상황을 모두 메소드로 분리한다면 private 메소드가 너무 많아지고 빼야하는 상황도 다양해질 것 같아 제 경우에는 해당 코드를 유지하고 싶다는 의견입니다.

``` java
GpuBoard gpuBoard = gpuBoardRepository.findByGpuServerId(jobRequest.getGpuServerId())
        .orElseThrow(() -> new IllegalArgumentException("board 가 없습니다."));

LabUser labUser = labUserRepository.findById(labUserId)
        .orElseThrow(() -> new IllegalArgumentException("user 가 없습니다."));

Job job = jobRepository.findByIdAndLabUserId(jobId, labUserId)
        .orElseThrow(() -> new IllegalArgumentException("job 이 없습니다."));

Job job = jobRepository.findById(id)
        .orElseThrow(() -> new IllegalArgumentException("job 이 없습니다."));
```

2021-07-15 02:41 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/domain/Job.java
> +    private LabUser labUser;
좋은 코멘트입니다!!

2021-07-15 02:43 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/domain/GpuBoard.java
> +                || modelName == null || modelName.isEmpty() || gpuServer == null) {
@Valid은 parameter에 대한 검증일 때 사용할 수 있습니다.
서비스 메소드에서 parameter로 사용되는 것들은 DTO 뿐이라서 도메인 엔티티는 @Valid를 사용할 수 없습니다.
혹시 제 말이 틀리다면 알려주세요! 저도 방법을 찾고 싶네요.

2021-07-15 02:46 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +        checkLab(labId);
@ecsimsw 저도 validateLab이 좋을 것 같은데 코기는 어떻게 생각하시나요?

2021-07-15 02:47 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/application/JobService.java
> +                .orElseThrow(() -> new IllegalArgumentException("job 이 없습니다."));
위에 있는 코기의 답변 참고 바랍니다 :)

2021-07-15 02:50 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/domain/Job.java
>      }
좋은 생각이네요!

2021-07-15 02:51 UTC, sjpark-dev commented on back-end/src/test/java/admin/gpuserver/application/GpuServerServiceTest.java
> +    @DisplayName("존재하지 GPU_Server_ID로 GPU 서버의 이름을 수정한다.")
오타입니다. 수정했습니다.

2021-07-15 02:52 UTC, sjpark-dev commented on back-end/src/test/java/admin/gpuserver/ui/GpuServerAcceptanceTest.java
> +
좋습니다!

2021-07-15 03:00 UTC, sjpark-dev commented on back-end/src/test/java/admin/gpuserver/domain/GpuBoardTest.java
> +    }
저는 방법의 차이라고 생각합니다.
위는 생성 과정이 올바르게 진행되는지에 포커스를 맞춘것이고,
아래는 객체가 생성되었는지에 포커스를 맞추는 것이라 생가합니다.

2021-07-15 03:01 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/domain/GpuServer.java
> +            throw new GpuServerServiceException("객체를 생성할 수 없습니다.");
별도의 예외를 발생 시키는 것에 동의합니다.

2021-07-15 03:07 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/domain/DeleteHistory.java
>  public class DeleteHistory extends BaseEntity {
삭제 시점을 기록하는 거라고 생각합니다.
GpuServer가 소프트 삭제된다면 GpuServer에는 삭제여부만 있을 뿐 언제 삭제했는지는 알 수가 없습니다.
추가로 기능을 구현을 통해 누가 삭제했는지도 DeleteHistory에 추가 할 수 있겠네요.

개인적으로 저도 소프트 삭제를 선호하지 않게 되었는데요.
일단 도메인 설계를 유지하기로 했으니 남겨 두었습니다.

#58 에 의견을 남겨보는 것은 어떨가요?

2021-07-15 03:14 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/domain/Job.java
> +    public void setName(String name) {
👍👍👍👍

2021-07-15 03:24 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/domain/Job.java
> +    public void cancel() {
아래 코드와 같이, 도메인에서 status 변경 테스트를 원하신 것은 아닐 것이라 생각하는데 맞는지요. 
DB 데이터 저장 확인을 말씀하신 것으로 생각하는데, 그 부분은 추후 JobServiceTest 에서 cancel 수행으로 해당 Job 상태 변경을 확인하겠습니다.

의도하신 부분과 다르다면 다시 커멘트 부탁드리겠습니다.

```
@DisplayName("수정 테스트 - Job status를 변경한다")
@Test
void 수정_Job_Status() {
    assertThat(testJob.status()).isNotEqualsTo(JobStatus.CANCEL);
    testJob.cancel();
    assertThat(testJob.status()).isEqualsTo(JobStatus.CANCEL);
}
```

2021-07-15 03:26 UTC, ecsimsw commented on back-end/src/test/java/admin/gpuserver/domain/DeleteHistoryTest.java
> +public class DeleteHistoryTest {
Soft 삭제는 아직 팀원끼리 협의가 덜 된 문제라고 생각하여 사실 집중하지 못했습니다.
Soft 삭제와 관련된 로직, 테스트는 이번 PR 후에 이슈 #58 과 함께 진행해보도록 하겠습니다.

2021-07-15 03:39 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/domain/GpuBoard.java
> +                || modelName == null || modelName.isEmpty() || gpuServer == null) {
Spring validation으로 도메인 생성 시 validation 어노테이션을 적용하고 싶다면 앞선 댓글처럼 파라미터에 @Valid를 달거나, 아래와 같은 꼴로 직접 유효 여부를 확인해야하는데 코드가 길어지고 의미가 없을 것 같다는 결론을 내렸습니다.

추가로 @Valid를 파라미터에 붙이는 것도 Argument Resolver 처럼 객체를 생성하고 인자에 넣어주는 시점에서 아래 로직이 수행되는 것이 아닌가 추측하고 있습니다.

```
Set<ConstraintViolation<User>> violations = validator.validate(job);
for (ConstraintViolation<User> violation : violations) {
    log.error(violation.getMessage()); 
}
```

2021-07-15 03:46 UTC, ecsimsw commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +        checkLab(labId);
일단 수정했습니다만, 저는 check가 더 좋다고 생각합니다.
제 개념에서 validate는 뭔가 객체 유효를 검증하는 느낌이라, 존재하는 labId인지만 확인하는 이번 상황에서는 조심스레 check를 응원해봅니다.. ㅎㅎ (그냥 제 개인 생각!!)

```
checkLabId(labId);

validateLab(lab);
```

2021-07-15 04:00 UTC, sjpark-dev commented on back-end/src/main/java/admin/gpuserver/domain/DeleteHistory.java
> +    }
여기서 말한 `객체를 생성할 수 없습니다`는 DeleteHistory 객체를 말하는 건데요.
제가 예외를 GpuServerServiceException으로 던져서 혼란을 드렸네요.
도메인 생성 전용 Exception을 새로 만들겠습니다.

2021-07-15 05:06 UTC, MyaGya commented on back-end/src/main/java/admin/gpuserver/domain/GpuServer.java
> +            throw new GpuServerServiceException("객체를 생성할 수 없습니다.");
도메인에서 쓰는 구조를 유지하려면 도메인에 대한 에러를 새롭게 만드는 것도 괜찮아 보이네요

2021-07-15 05:17 UTC, knae11 commented on back-end/src/main/java/admin/gpuserver/application/JobService.java
> +                .orElseThrow(() -> new IllegalArgumentException("board 가 없습니다."));
이부분도 이슈로 나눠 얘기해 보는게 좋겠네요!ㅎㅎㅎ

2021-07-15 05:35 UTC, wannte commented on back-end/src/main/java/admin/gpuserver/domain/Job.java
> +    private LabUser labUser;
저는 반대로 LabUser 객체를 가져오는게 좋을 것 같다는 생각이에요. db를 찌르는 부분에서 id만을 사용하긴하지만,

jobResponses 를 리턴해줄 때 userId만 가지고 있게 되면, 어떤 사람의 job인지를 다시 api호출해야하지 않을까요?

2021-07-15 05:45 UTC, wannte commented on back-end/src/main/java/admin/gpuserver/application/GpuServerService.java
> +        checkLab(labId);
내꺼 코드리뷰에도 적었는데 나도 checkLabId 한표~

2021-07-15 08:26 UTC, MyaGya approved these changes

2021-07-15 10:53 UTC, knae11 approved these changes

2021-07-15 10:53 UTC, merged